// <auto-generated />
using CMShop.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMShop.ProductAPI.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250918124244_AddStockColumn")]
    partial class AddStockColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMShop.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 6L,
                            CategoryName = "Acessórios para Celulares",
                            Description = "Power Bank com 2 saídas USB, ideal para carregar dispositivos em qualquer lugar. Alta capacidade e carregamento rápido.",
                            ImageURL = "https://images.pexels.com/photos/518530/pexels-photo-518530.jpeg",
                            Name = "Carregador Portátil Power Bank Inova 20000mAh",
                            Price = 69.6m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Eletrônicos",
                            Description = "Fone de ouvido com conexão Bluetooth, som JBL Pure Bass, até 40h de bateria e design dobrável para maior praticidade.",
                            ImageURL = "https://images.pexels.com/photos/20285555/pexels-photo-20285555.jpeg",
                            Name = "Fone de Ouvido Bluetooth JBL Tune 510BT",
                            Price = 219.9m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Smartwatches",
                            Description = "Relógio inteligente com monitoramento de saúde, GPS integrado, resistência à água 5ATM e até 9 dias de bateria.",
                            ImageURL = "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg",
                            Name = "Smartwatch Amazfit Bip U Pro GPS",
                            Price = 349.99m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Acessórios para Celulares",
                            Description = "Cabo USB-C resistente com carregamento turbo de 3A. Compatível com celulares Android, ideal para uso diário.",
                            ImageURL = "https://images.pexels.com/photos/4219863/pexels-photo-4219863.jpeg",
                            Name = "Cabo USB-C Turbo 3A 1m Nylon Reforçado",
                            Price = 24.9m,
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
